### PR TITLE
Redesign site

### PR DESCRIPTION
**Pull request by qjack001**
Let me know what you think.

### CODE REVIEW

**Comment by HoloPollock** [comment]
its looks good on desktop on mobile the gradient is a little bit awkward

**Comment by qjack001** [comment]
How so

**Comment by HoloPollock** [comment]
the start point of the gradient is odd but fine

**Review by HoloPollock — APPROVED** [review]

**Comment by HoloPollock** [comment]
im fine leaving it where it is but something still feels off

**Comment by qjack001** [comment]
> the start point of the gradient is odd but fine

Ah, ya I double up on the gradients so that the text has enough contrast. Think of it more like a blurry blob than a gradient.

**Pull request merged**
